apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grpc-client
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      name: grpc-client
  template:
    metadata:
      labels:
        name: grpc-client
    spec:
      serviceAccountName: grpclb-sa
      containers:
        # ------------------- agent ------------------- #
        - name: grpc-agent
          image: grpc-client:v0.1
          imagePullPolicy: IfNotPresent