kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grpclb-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: grpclb-sa
    namespace: default
roleRef:
  kind: Role
  name: grpclb-role
  apiGroup: rbac.authorization.k8s.io