---
# ------------------- Dosec Service ------------------- #
# 注意事项：
# 1. 修改 web_api 链接
# 2. 修改镜像版本

apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  type: NodePort
  ports:
    - name: server
      port: 30000
      protocol: TCP
      targetPort: 30000
      nodePort: 30001
  selector:
    app: grpc-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
#      nodeSelector:
#        node-role.kubernetes.io/master: ""
#        #node-role.kubernetes.io/control-plane: "" # k8s v1.24 kubeadm applies on the control plane nodes
#      tolerations:
#        - effect: NoSchedule
#          key: node-role.kubernetes.io/master
      containers:
        - name: grpc-server
          image: grpc-server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30000
              protocol: TCP